spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catcate
    username: root
    password: 18697098685
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

# 支付宝配置
alipay:
  app-id: 9021000158625212
  merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCbAoJYPTX9l5zOzm9CnX8jpvwDVcW+bWTFNxW1vG9wQJ6k1JRyRXtlVxm00G+RndEE8X6SqhDfI/UPW660irS7INlV2pE3YxtLpfl5iYCHsOsxt03y5H4MuVfCkoRkskO9e1UPK1vE5yejEDpNj9X5sAjTAwEim4ibJbaWJ6TyYkGBuScjm+81CcVlEnJHe4ScOrfhCoEffdNYf8r4y125pspris4HJopNadrvzYGh9bpBZ0UQRW71Nucgx33h0ThzokOmQdk3we6nER4X+OTFOrkTGWkDs1V2tZFMpl8vxB4tYKAcadBw6S1sFxNNeCcLHgGkvogYw+ZUiL6STTNZAgMBAAECggEAGmS/+vRZOBfTrGb8DNSybEinio3VQMpxqR7rBGnUc8GdAaXsrNRl4WiGSQJgrOO5TmUsTx7EBqqhtH7A7Z7cjSxXtUWlClBGuofFRcuC5hfaxDlY/W2ohNQePFQkVN0BqcbRQeb5FjrhxeMiekhuf7hYmE1fqRvgk8JFJ6YScO7Dv4m1zQxHdWghoq5EUKW5iTJT7jsto8wMuVUhaiA1ljTfRiEcnHxwrACh75aKSVwW5K+h5JgnSTyAP66wlJInHZ65+GpoaIBpZgHBgIai0p033r7EMrNJ98N7hYmx6jaKOhzsYvLHQj7qRsHz57AdDj7mxL1gEcJIk4Y2AlIIcQKBgQDfNWt1wQJx8ito5JiUvWbVRQxqyjbVbGN7WcfaY2oYEJMRoImcfV5Y3Qxq+4Ej9Vy3NsUhfjSihEkHteIl7QeGln96HiA7kRwZREeC+SU3lLF4Qn2+5Mr5xLY69GIYF2PsnnDwnMMO8PgTlcIhnREOFVu9yQe2fQxlXIYiF4/nxQKBgQCxyDiOba2klulNo+wcvoAXT8BFx/Pn667OheQVlOgmSle1VC8JK8qBrURFtvFcgaqOWF5nSZ3SB6JiovcjzheiCiZl/KneAL3gzQwZv7uUkWpi4h7X2sjGn2ee/7WBNQquko65kp6y4r7HcLKHV57CMDycGRntxuJIAqjmMzVChQKBgElBmgwilW/aQB8D74PZiZdzOvkNduOi2B+SvsHRIO/W+L2vR5rBlqZpnfq6oo6vp4dGBXrRlerEqcdLDXbPDUpBuILWwlNqc6NjQmkc5fcQ6RIEGIr/QhKpWfmNXWh0vMna0kxV1rrfoTukSfuINiG+Jsbp5IsjDV9y917XBtbVAoGAIVupSQhJYa2zXw8X+ZjBHh6nvDA1ktnFNhknX+lN2glvBaYjITxnRgfF3LLj/PCTmRv5srW8eDFYhduANeawxoXTCKXtFavb9PdkgtxYDRtv89fr46K4s5QrdEkUvIbAV1tGjol1X6luFKwPw5dsQZGdfciz9cqwoMRm/rKzFqUCgYBlDFJEJy1JQ8wbnEuZh1cRDFels8YNq19MBm9t9Dzq/QFVK21Voau8mTW9MOD0zAh6cC+mDVz3um4Mx9U5rGYpq4ycAOmIPepulodYJAlX+F5ELFqs0DVcqI8ww3jqTdhbMRS6tBWOnFZ4p8wT1iI4yKVTxB53USlvgP2EuN+8KQ==
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsbGI3FIRyXhP7H7He9zjSsqPOpXsbwfJrnWWBsQOwV+1OuKfHlg7jihWrfvdgugzWx6e7Q6/+ZpSrBagH9p3CPUqHeS70t3aX6x2ALSscI/l3YoFIUjL+cX+ZERYuqqBDgqugqjncZ8wvEI8V4LpxT647wHp6MbQfA2wp5sCFW6QZjSaMMCTgoPDrPb3Luym2gETmT4QmpSdvowTBplsqIOTmLQ7B6rxFGECkQl+rYlp8MC4zVypHjgu42n1mEDV6WVLhqq1eg1dU4LCKI03vHityplrKbxEf2EsMOq9KNq5G2wBZ3deKXQ55wRooZKhqYqGbcw7tbiz406XuFbNRQIDAQAB
  notify-url: http://g22bd859.natappfree.cc/catcatecutomer/payment/alipay/notify
  return-url: http://localhost:8083/catcatecutomer/payment/alipay/return